# Generated by Django 4.2.11 on 2024-03-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, help_text='Снимка на артикула', upload_to='items', verbose_name='Снимка')),
                ('name', models.CharField(blank=True, default='', help_text='Наименование на артикула', max_length=100, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Цена на артикула', max_digits=6, verbose_name='Цена')),
                ('hits', models.IntegerField(default=0, help_text='брой продадени (попълва се автоматично)', verbose_name='Брой покупки')),
            ],
            options={
                'verbose_name': 'Стока',
                'verbose_name_plural': 'Стоки',
            },
        ),
    ]
