# Generated by Django 4.2.11 on 2024-03-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Собствено име')),
                ('last_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Фамилно име')),
                ('company', models.CharField(blank=True, default='', max_length=50, verbose_name='Фирма')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='Адрес')),
                ('email', models.CharField(blank=True, default='', max_length=100, verbose_name='Е-mail адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=100, verbose_name='Телефон')),
                ('note', models.TextField(blank=True, default='', verbose_name='Бележки')),
                ('order_details', models.CharField(blank=True, default='', max_length=50, verbose_name='Описание на поръчката')),
            ],
            options={
                'verbose_name': 'Поръчка',
                'verbose_name_plural': 'Поръчки',
            },
        ),
    ]
