# Generated by Django 4.2.11 on 2024-03-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_orderreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderReview',
            new_name='Order',
        ),
    ]
