# Generated by Django 4.2.11 on 2024-03-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
    ]
